### ISSUE TITLE
Encryption error

### ISSUE THREAD

**Issue by ChrisLuck** [janimo/textsecure-qml#17]
I have two friends in textsecure (Friend A and Friend B).
Friend A has a Nexus 5 with up to date stock ROM and friend B has an One Plus One with up to date stock ROM. (Both are Android phones)

Textsecure works flawless when communicating with friend B. Never had any issue and i want to thank you very much for making this possible :)

When communicating with friend A however, the session gets periodically 'destroyed'.
From this point on my friend only sees the text "Fehlerhaft verschlüsselte Nachricht ..." (erroneously encrypted message) whenever i write something to him.

This can be fixed by deleting the session-file and the remote_xxxx file of this friend.

This is the log from .cache/upstart/...
http://paste.ubuntu.com/12751494/

This is the textsecure log from Friend A:
https://gist.github.com/anonymous/ec86f09158a02f4a2d00

**Comment by janimo** [comment]
Thanks for the detailed report!
I also see this quite often and it's at the top of things to investigate, since it can be quite annoying.
Does you friend B also run TextSecure 2.28.1 ?
Are group chats involved at any point?

I think the issue can be worked around from Android too, by doing a session reset from the lock icon, and then you may not need to manually remove those files.

**Comment by ChrisLuck** [comment]
I never used group chats.

Sadly, today the error also appeared with friend B, for the first time :(

Here is his log:
https://gist.github.com/a6397ec2c6b2ecbb1cd0

The error in his log is quite different to the errors in friend A's log.... So maybe this was an unrelated second bug.
His version is 3.0.3 at the moment.

I think the problem is not related to any specific version of the android client. I remember, that it also appeared when friend A had version 2.27.2 installed.

**Comment by janimo** [comment]
thanks. Good to know it's unrelated to group chats. I asked for the Android app version since I saw a recent textsecure issue involving bad encryption errors
https://github.com/WhisperSystems/TextSecure/issues/4227

This is my library bug, it probably does not handle out of order messages, gets confused, and subsequently uses bad encryption keys for outgoing messages.

**Comment by janimo** [comment]
Some backend fixes were added in 0.3.2, they may help.

**Comment by janimo** [comment]
Hi,
do you still get errors with the new version of the app?

**Comment by ChrisLuck** [comment]
I can't tell because that friend A got a new phone and we didn't communicate much because of that.
This particular bug didn't appear again but there are other funny things going on right now ;) i will open a new issue for that.

**Comment by janimo** [comment]
I have not seen such errors since 0.3.2
