### ISSUE TITLE
Registered with wrong number

### ISSUE THREAD

**Issue by homerich** [janimo/textsecure-qml#37]
hi, i've installed textsecure on my aquaris 4.5. i can send messages, but i can't receive any. there is also no way altering the options in the options menu.

**Comment by AnneGilles** [comment]
same here (on aquaris E5, ubuntu 15.04 (OTA-8.5), TextSecure 0.3.8).

message recipients complain they don't get my key (it is not published?), so they can't send messages to me. I got SMS in response instead. 

one recipient claimed my messages made her signal crash.
another one said there was a lock on my message (message was encrypted) but the send button had an open lock (no encryption possible, hence unencrypted SMS was sent.)

**Comment by janimo** [comment]
@homerich maybe try reset session from the menu? Does you contact get your messages but you get no  answers from them? Make sure you use the latest version and please mail me (jani@ubuntu.com) the logfile if you can get it, it's /home/phablet/.cache/upstart/application-click-textsecure.jani_textsecure_0.3.9.log
The settings menu currently only has a single option - 'Enter sends'. The others will come too eventually.

**Comment by janimo** [comment]
@AnneGilles I am not sure what is meant by "they don't get the key". Do both you and your contact have eachother listed in the contacts shown by Signal? If you send a message to a contact, they should be able to reply within that same conversation.
If you could reproduce the step to crash your contact's signal I'd be interested in both your logfile (see comment above) and the version of Signal they use. I know we have previously sent broken messages in some corner cases but I have not yet succeeded crashing Android Signal.
I also have not heard of a case of getting an encrypted message but not being able to send an encrypted answer. This would be very useful to investigate, so mailing me the logfile would help.

**Comment by homerich** [comment]
@janimo your email seems not to work!

**Comment by homerich** [comment]
@janimo that's correct: my contavćt gets messages sent from me, but i cannot receive messages.
also i resetted the session, nothing happens.
[application-click-textsecure.jani_textsecure_0.3.9.txt](https://github.com/janimo/textsecure-qml/files/86214/application-click-textsecure.jani_textsecure_0.3.9.txt)

**Comment by janimo** [comment]
@homerich this is a number I use for testing, you can try messaging me to see if we can have a working session 
+40701234665

**Comment by janimo** [comment]
@homerich so when I answer your text I get my message sent out properly, but get no delivery indication, suggesting the server does not relay it to you, meaning your number somehow got out of sync. This happens oftne enough that OWS has a page that tries to fix it:
https://whispersystems.org/textsecure/unregister/
Maybe this will help you too?

**Comment by janimo** [comment]
@AnneGilles you could try the same form in the comment above, or similarly text me on my number above.
I need to see why some numbers get unregistered at the server - it happens often on Android too.

**Comment by homerich** [comment]
@janimo well, it worked once (right after unsuscribing), but afterwards it's nonfunctional again...

**Comment by homerich** [comment]
@janimo i refreshed the contacts list on my contacts phone for several times, but i can't manage to connect with my number. i also reinstalled the app. what i noticed: when i install signal on my android phone, i'm asked to connect to signal, afterwards i receive a key. after installing the ubuntu app, there's no request for my phone number. could this be the reason, why it's not working?

**Comment by AnneGilles** [comment]
after successful messaging (w/ textsecure) with @janimo and one other peer (signal 3.8.1 on cyanogenmod) I still have problems with other peers. me on 0.3.9/ubuntu, them on android 5.1.1/signal 3.9.1 and android 4.1.2/emui1.6/signal 3.9.1.

hypothesis: those peers that I can write to but who were unable to textsecure-message me seem to have problems to find me/my key on the server. the lookup fails due to wrong/faulty number.

I confirmed this by having one peer change my number from +49178... to +490178... (so including a zero (0) between the country-prefix and the mobile number). now that peer can text securely to me!

so i think there is/was a bug in the registration process when my number was registered on the server. (yes, that is speculation; no idea why some few peers did not have problems with this.) that zero in there feels non-standard to me -- and others apps too.

as I do not remember how registration looked like (and how my number got into it), I guess I have to unregister with signal ( https://whispersystems.org/textsecure/unregister/ ) and uninstall/reinstall the app. then register again, making sure the correct number is used.

**Comment by janimo** [comment]
So if you know your number should not have a 0 there, and it does not have a 0 when  you register on Android/Signal then it is a bug in the Ubuntu app.

The way to reregister forcefully on Ubuntu is to adb shell in the phone and rm -Rf /home/phablet/.local/share/textsecure.jani/.storage and rm -Rf /home/phablet/.config/textsecure.jani/config.yml and start the app.
I need to make this accesible from the UI

**Comment by AnneGilles** [comment]
thanks for your help! I ssh'ed in and removed storage and config, started textsecure and was able to re-register. peers confirm that I no longer have that 0 in my number. works!

so maybe there is or was no bug in the app, but the registration screen should tell people to drop the leading zero, so honks like me don't step into that trap.

maybe the settings dialogue should show users which number they are registered with, i.e. show whats in config.yml.

**Comment by AnneGilles** [comment]
sorry, @homerich for hijacking your thread/issue.

**Comment by homerich** [comment]
@AnneGilles no prob, it's finally working!!!
@janimo thanks a lot!!!

**Comment by janimo** [comment]
I am glad we found what the issue was for both of you, but the bug might still exist.
To recap:
Both of your numbers showed up with +490 here, and I could talk to you.
This means you could register that wrong number but still get an SMS code for the right number (without the 0).
How did you introduce the number in the UI?
What version of TextSecure did you use when you registered (if you remember)
This is possibly a widespread issue, but most people just give up on the app instead of filing an issue, so thanks both :)

**Comment by homerich** [comment]
@janimo in the android version (signal 3.9.1) i registered with +490, but it showed the number without the 0 after pressing "register". the version of textsecure on ubuntu is 0.3.9.
once again: thanks for the quick help!

**Comment by AnneGilles** [comment]
I registered with 0.3.8, now on 0.3.9.
I must have entered the leading zero, not knowing what I did. 

about wrong numbers and getting SMS codes:
the OWS unregister-tool sends SMS with codes to the same phone, for both the "+49178..." and "+490178..." variants. So maybe that zero is automagically dropped somewhere -- the server knows what to do.

**Comment by janimo** [comment]
Version 0.3.10 includes a verification dialog when entering the registration phone number and a UI for unregistering which also lists the currently used number. This should significantly decrease the number of wrongly registered and confused users.
